### ISSUE TITLE
Cannot authenticate OR Cannot connect to minetest server

### ISSUE THREAD

**Issue by lgblkb** [miney-py/miney#2]
Hi @Netzvamp , first of all thank you for making Minetest available for Python users). 
On Ubuntu 20.04 when trying to run 

```
import miney

mt = miney.Minetest('127.0.0.1', 'AlizhanKing', '12345', )
```

I'm receiving this kind of error : 
```
Traceback (most recent call last):
  File "/home/lgblkb/PycharmProjects/minetester/main.py", line 9, in <module>
    main()
  File "/home/lgblkb/PycharmProjects/minetester/main.py", line 5, in main
    mt = miney.Minetest()
  File "/home/lgblkb/.virtualenvs/minetester/lib/python3.8/site-packages/miney/minetest.py", line 47, in __init__
    self._authenticate()
  File "/home/lgblkb/.virtualenvs/minetester/lib/python3.8/site-packages/miney/minetest.py", line 87, in _authenticate
    if "auth_ok" not in result:
TypeError: argument of type 'bool' is not iterable
```
`sockstat -p 29999` gives:

```
USER     PROCESS              PID      PROTO  SOURCE ADDRESS            FOREIGN ADDRESS           STATE
lgblkb   minetest             22805    tcp4   127.0.0.1:29999           *:*                       LISTEN
```

`cat .minetest/minetest.conf` gives:
```
name = AlizhanKing
menu_last_game = minetest
screen_w = 1848
screen_h = 1016
enable_damage = false
enable_server = true
server_announce = true
fixed_map_seed = 
selected_world_path = /home/lgblkb/.minetest/worlds/TheWorld
mainmenu_last_selected_world = 1
creative_mode = true
mg_name = v7
port = 30000
maintab_LAST = settings
main_menu_technical_settings = false
world_config_selected_mod = 41
enable_client_modding = true
secure.trusted_mods = mineysocket
enable_rollback_recording = true
```
`minetest --version`:

```
Minetest 5.1.1 (Linux)
Using Irrlicht 1.8.4
BUILD_TYPE=None
RUN_IN_PLACE=0
USE_GETTEXT=1
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=1
STATIC_SHAREDIR="/usr/share/games/minetest"
```
Do you have any ideas? Thanks!

**Comment by hgerloni** [comment]
Probably you have the old UDP version of miney installed. Try `pip install git+https://github.com/miney-py/miney.git`

**Comment by Netzvamp** [comment]
The version on pypi was updated, so this shouldn't happen anymore ...
