### ISSUE TITLE
connecting to a server on a different machine in the LAN fails with timeout

### ISSUE THREAD

**Issue by NilsBe** [miney-py/miney#7]
I am trying to connect miney with a different machine in my LAN.

It works without problems when connecting to a server on the same machine. 
`  mt = miney.Minetest()`
I can also connect the minetest client with the server on a different machine.
But I get constantly an error when I try to connect miney with the server on the different machine.
`  mt = miney.Minetest('192.168.1.78', 'user', 'user', 29999)`

```
Traceback (most recent call last):
  File "<pyshell#17>", line 1, in <module>
    mt = miney.Minetest('192.168.1.78', 'user', 'user', 29999)
  File "c:\Users\Nils\Downloads\miney_windows_x64\miney_x64\Python\lib\site-packages\miney\minetest.py", line 49, in __init__
    self._connect()
  File "c:\Users\Nils\Downloads\miney_windows_x64\miney_x64\Python\lib\site-packages\miney\minetest.py", line 93, in _connect
    self.connection.connect((self.server, self.port))
socket.timeout: timed out
```

Any ideas?

**Comment by kig2929kig** [comment]
Please tell me the solution?

**Comment by kig2929kig** [comment]
> 미안해요. 문서를 완전히 읽지 않았습니다. 해결 된 것 같습니다.

Please tell me the solution?
